version: '7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.ft
    ports:
      - 4200:80
    networks:
      - app_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.bk
    ports:
      - 7018:80
    networks:
      - app_net
      
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tus3cretoPassw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"

networks:
  app_net:
    driver: bridge
