FROM mcr.microsoft.com/mssql/server:2019-latest

# Variables de entorno para la configuración de SQL Server
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Tus3cretoPassw0rd
ENV MSSQL_PID=Developer

# Exponer el puerto en el que SQL Server escucha
EXPOSE 1433


